begin;
create extension if not exists pgtap with schema extensions;
select plan(12);
select has_table('public','weekly_comments','weekly comments exist');
select has_table('public','game_results','game results exist');
select has_table('public','score_events','score events exist');
select has_table('public','payout_schedules','payout schedules exist');
select has_table('public','commissioner_audit_events','commissioner audit exists');
select ok((select relrowsecurity from pg_class where oid='public.weekly_comments'::regclass),'comments use RLS');
select ok((select relrowsecurity from pg_class where oid='public.game_results'::regclass),'results use RLS');
select ok((select relrowsecurity from pg_class where oid='public.score_events'::regclass),'scores use RLS');
select ok((select relrowsecurity from pg_class where oid='public.payout_schedules'::regclass),'payouts use RLS');
select col_type_is('public','weekly_comments','body','text','comment body is text');
select col_type_is('public','score_events','decision_value','numeric(6,2)','score values are exact');
select is((select sum(amount) from public.payout_schedules schedule join public.seasons season on season.id=schedule.season_id where season.year=2026),0::numeric,'default payout schedule balances');
select * from finish();
rollback;
