import type { Game } from "./model";

export const MOCK_GAMES: Game[] = [
  {
    id: "sf-lar",
    away: { abbreviation: "SF", name: "49ers" },
    home: { abbreviation: "LAR", name: "Rams" },
    awaySpread: 8.5,
    total: 45.5,
    badge: "TNF",
    kickoff: "Thu · 8:15 PM ET",
    location: "SoFi Stadium",
  },
  {
    id: "min-cle",
    away: { abbreviation: "MIN", name: "Vikings" },
    home: { abbreviation: "CLE", name: "Browns" },
    awaySpread: -3.5,
    total: 36.5,
    badge: "INTL",
    kickoff: "Sun · 9:30 AM ET",
    location: "London",
  },
  {
    id: "hou-bal",
    away: { abbreviation: "HOU", name: "Texans" },
    home: { abbreviation: "BAL", name: "Ravens" },
    awaySpread: -2,
    total: 40.5,
    badge: "1 PM",
    kickoff: "Sun · 1:00 PM ET",
    location: "Baltimore",
  },
  {
    id: "mia-car",
    away: { abbreviation: "MIA", name: "Dolphins" },
    home: { abbreviation: "CAR", name: "Panthers" },
    awaySpread: -1,
    total: 44.5,
    badge: "1 PM",
    kickoff: "Sun · 1:00 PM ET",
    location: "Charlotte",
  },
  {
    id: "dal-nyj",
    away: { abbreviation: "DAL", name: "Cowboys" },
    home: { abbreviation: "NYJ", name: "Jets" },
    awaySpread: -2.5,
    total: 47.5,
    badge: "1 PM",
    kickoff: "Sun · 1:00 PM ET",
    location: "New York",
  },
  {
    id: "ten-ari",
    away: { abbreviation: "TEN", name: "Titans" },
    home: { abbreviation: "ARI", name: "Cardinals" },
    awaySpread: 7.5,
    total: 42,
    badge: "4 PM",
    kickoff: "Sun · 4:05 PM ET",
    location: "Arizona",
  },
  {
    id: "ne-buf",
    away: { abbreviation: "NE", name: "Patriots" },
    home: { abbreviation: "BUF", name: "Bills" },
    awaySpread: 8,
    total: 49.5,
    badge: "SNF",
    kickoff: "Sun · 8:20 PM ET",
    location: "Buffalo",
  },
  {
    id: "kc-jax",
    away: { abbreviation: "KC", name: "Chiefs" },
    home: { abbreviation: "JAX", name: "Jaguars" },
    awaySpread: -3.5,
    total: 46.5,
    badge: "MNF",
    kickoff: "Mon · 8:15 PM ET",
    location: "Jacksonville",
  },
];
